# includes:
#   - headers/data.yaml
#   - headers/device.yaml
#   - headers/misc.yaml
#   - headers/model.yaml
#   - headers/optimizer.yaml
#   - classifiers/DynamicWeightsModel.yaml
#   - backbones/resnet12.yaml

# way_num: 5
# shot_num: 1
# query_num: 15
# test_way: 5
# test_shot: 1
# test_query: 15
# episode_size: 1
# train_episode: 600
# test_episode: 200
# #way_num 对应参数 --nKnovel
# #shot_num 对应参数 --nExemplars
# #query_num_train = args.train_nTestNovel
# #以下两个未改


# classifier:
#   name: DynamicWeightsModel
#   kwargs: ~
# backbone:
#   name: resnet12
#   kwargs:
#     avg_pool: false
#     is_flatten: false
#     keep_prob: 0.0
#     maxpool_last2: true


augment: true
augment_times: 1
augment_times_query: 1
backbone:
  kwargs:
    avg_pool: false
    is_flatten: false
    keep_prob: 0.0
    maxpool_last2: true
  name: resnet12
batch_size: 4
classifier:
  kwargs: null
  name: DynamicWeightsModel
data_root: ./data/fewshot/miniImageNet--ravi
dataloader_num: 1
deterministic: true
device_ids: 0,1,2,3
episode_size: 1
epoch: 90
image_size: 84
includes:
- headers/data.yaml
- headers/device.yaml
- headers/misc.yaml
- headers/model.yaml
- headers/optimizer.yaml
- classifiers/DynamicWeightsModel.yaml
- backbones/resnet12.yaml
log_interval: 100
log_level: info
log_name: null
log_paramerter: false
lr_scheduler:
  kwargs:
    T_max: 100
    eta_min: 0
  name: CosineAnnealingLR
n_gpu: 1
optimizer:
  kwargs:
    lr: 0.01
    momentum: 0.9
    nesterov: true
    weight_decay: 0.0005
  name: SGD
  other: null
parallel_part:
- emb_func
pretrain_path: null
query_num: 15
rank: 0
result_root: ./results
resume: false
save_interval: 10
save_part:
- emb_func
seed: 1
shot_num: 1
tag: null
tb_scale: 3.3333333333333335
test_episode: 200
test_epoch: 5
test_query: 15
test_shot: 1
test_way: 5
train_episode: 600
use_memory: false
val_per_epoch: 1
warmup: 0
way_num: 5
workers: 8
