#epoch: 50
#test_epoch: 5
#
#parallel_part:
#  - emb_func
#
#pretrain_path: ~
#resume: False
## few shot settings
#way_num: 5
#shot_num: 1
#query_num: 15
#test_way: ~ # use ~ -> test_* = *_num
#test_shot: ~
#test_query: ~
#episode_size: 1
#train_episode: 100
#test_episode: 100
#
## general model setting
#batch_size: 128
#val_per_epoch: 1


epoch: 90
test_epoch: 5

parallel_part:
  - emb_func

pretrain_path: ~
resume: False
# few shot settings
way_num: 5
shot_num: 1
query_num: 6
test_way: 5 # use ~ -> test_* = *_num
test_shot: 1
test_query: 15
#episode_size: 4
train_episode: 1200
test_episode: 2000

# general model setting
batch_size: 4
val_per_epoch: 1
